---
- name: install glance packages
  apt: name={{ item }} state=latest force=yes
  with_items:
    - glance
    - python-glanceclient

- name: update glance conf
  template: src={{ item }} dest=/etc/glance/{{ item }} backup=yes
  with_items:
    - glance-api.conf
    - glance-registry.conf
  notify:
    - restart glance-registry
    - restart glance-api

- name: manually stop glance-api
  service: name=glance-api state=stopped

- name: manually stop glance-registry
  service: name=glance-registry state=stopped

- name: remove default sqlite db
  shell: rm /var/lib/glance/glance.sqlite || touch glance.sqllite.db.removed

- name: sync glance db
  shell: su -s /bin/sh -c "glance-manage db_sync" glance

- name: start glance api
  service: name=glance-api state=started

- name: start glance registry
  service: name=glance-registry state=started

- name: upload cirros img to glance
  shell: glance --os-username=admin --os-password={{ ADMIN_PASS }} --os-tenant-name=admin --os-auth-url=http://controller:35357/v2.0 image-create --name="{{ build_in_image_name }}" --disk-format=qcow2 --container-format=bare --is-public=true --copy-from {{ build_in_image }} && touch glance.import.completed

