---
- hosts: all
  remote_user: vagrant
  sudo: True
  roles:
    - common
    - database
    - mq
    - glance
    - keystone 
    - nova-controller
    - neutron-controller
    - cinder-controller
    - dashboard
    - nova-compute
    - neutron-compute
    - neutron-network
    - cinder-volume
