---
- name: install cinder packages
  apt: name={{ item }}
  with_items:
    - cinder-api
    - cinder-scheduler

- name: upload cinder conf
  template: src=cinder.conf dest=/etc/cinder/cinder.conf
  notify:
    - restart cinder-scheduler
    - restart cinder-api

- name: manually stop cinder scheduler
  service: name=cinder-scheduler state=stopped

- name: manually stop cinder api
  service: name=cinder-api state=stopped

- name: sync cinder db
  shell: su -s /bin/sh -c "cinder-manage db sync" cinder && cinder

- name: upload cinder keystone register script
  template: src=cinder_init.sh dest=/opt/cinder_init.sh mode=0744

- name: run cinder register script
  shell: /opt/cinder_init.sh && touch cinder_init_complete
